#PostreSQL Config

spring.application.name=ehr

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/EHR_project
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=your-very-long-secret-key-that-is-at-least-64-characters-long-for-hs512
