
spring.application.name=ehr

server.port=8080

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}

jwt.secret=${JWT_SECRET}
frontend.url=${FRONTEND_URL}
backend.url=${BACKEND_URL}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

logging.level.org.springframework.beans.factory.support=INFO
