services:
  backend:
    build: ./backend
    container_name: ehr-backend
    env_file: ehr-env.env
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allows container to see VPS Postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/ehr_db
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=${JWT_SECRET}
  
  frontend:
    build: ./frontend
    container_name: ehr-frontend
    ports:
      - "8082:80"
    depends_on:
      - backend