import { Patient } from "../patient/patient";

export interface SurgeryCase {
  surgeryCaseId?: number;  // optional because it's generated by backend
  procedure: string;
  scheduledStartTime: string;
  actualStartTime: string | null;
  endTime: string;
  actualEndTime: string | null;
  surgeon: string;
  anesthesia: string;
  nurse: string;
  scrub: string;
  patient: string;
  roomId: number;
  surgeryCaseStatus?: string; // optional
  fullPatient?: Patient;
  notes?: string;
  dateOfCase: Date;
}