export interface SurgeryCase {
  surgeryCaseId?: number;  // Optional since it's generated by backend
  procedure: string;
  startTime: string;
  endTime: string;
  surgeon: string;
  anesthesia: string;
  nurse: string;
  scrub: string;
  patient: string;
  roomId: number;
}